### ISSUE TITLE
config文件有嘛老哥

### ISSUE THREAD

**Issue by TattooPro** [flufy3d/DQN_WUKONG#3]
或者我怎么才能直接自己训练呢

**Comment by flufy3d** [comment]
窗口坐标 根据自己的 定一下  然后 restart逻辑 根据你的boss 自己写一下 就可以开始训练了 python training.py

**Comment by TattooPro** [comment]
感谢！我说呢，原来是yaml包下错了，虽然叫yaml但是得安装pyyaml
